{
 "title": "KAP_METRIC",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "show tag values from query_metric with key=project"
   },
   {
    "name": "time_gap",
    "label": "interval",
    "query": "1s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "queries_count_on_certain_time_range",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$time_gap" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "query_metric",
     "select": [
      [
       { "params": [ "query_duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$time_gap" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "query_metric",
     "query": "SELECT mean(QPS) FROM (\n   SELECT count(\"query_duration\") as QPS FROM \"query_metric\" WHERE (\"project\" =~ /^$project$/) AND $timeFilter GROUP BY time(1s) fill(0)\n)\nGROUP BY time($time_gap) fill(null)",
     "select": [
      [
       { "params": [ "query_duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "avg_query_response_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$time_gap" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "query_metric",
     "select": [
      [
       { "params": [ "query_duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "number_of_parallel_user",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$time_gap" ], "type": "time" },
      { "params": [ "submitter" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "query_metric",
     "query": "SELECT count(\"first\") FROM (\n  SELECT first(\"query_duration\") FROM \"query_metric\"\n  WHERE (\"project\" =~ /^$project$/) AND $timeFilter \n   GROUP BY time($time_gap), \"submitter\" \n)\nGROUP BY time($time_gap)",
     "select": [
      [
       { "params": [ "query_duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  }
 ]
}